version: 2

sources:
  - name: raw # name to reference the database in sql file
    schema: gz_raw_data #actual name/schema of the database
    description: greenweez raw data source

    tables:
      - name: sales #name to reference on sql file
        identifier: raw_gz_sales #name of the table on bigquery
        description: sales of greenweez / there is one row per product_id found in each orders_id.
        columns:
          - name: sales_id
            description: unique key of this table

          - name: data_date
            description: date of purchase

          - name: orders_id
            description: foreign key of each ship/order
          
          - name: pdt_id
            description: foreign key of each product

          - name: revenue
            description: the price paid by customer for each product. revenue = quantity * selling_price
          
          - name: quantity
            description: the number of an specific product purchased per order
        
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          # or an alternative is to install a package dbt_utils and use this function bellow
          # - dbt_utils.unique_combination_of_columns:
              # combination_of_columns:
                # - orders_id
                # - products_id
        
        # adding freshness test to warn me in case the table is older than a specified period
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date as timestamp)"
        # run dbt source freshness to test if data in sales is more than 90days
        

      - name: product
        identifier: raw_gz_product
        description: product ids and it's purchase price
        columns:
          - name: products_id
            description: unique identifier of this table
            tests:
              - unique
              - not_null
          
          - name: purchase_price
            description: purchase price of each product

      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: primary key of this table
            tests:
              - unique
              - not_null
                  
          - name: shipping_fee
            description: the fee price a customer pay for shipping

          - name: logcost
            description: the cost of logistics (preparing the parcel at the warehouse)

          - name: ship_cost
            description: the shipping cost paid by greenweez to the carrier